# Generated by Django 3.0.5 on 2020-04-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_index', models.IntegerField(blank=True, null=True)),
                ('opsname', models.CharField(blank=True, max_length=100, null=True)),
                ('opstype', models.CharField(blank=True, max_length=100, null=True)),
                ('opssubm', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('autonom', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('city_1', models.CharField(blank=True, max_length=100, null=True)),
                ('actdate', models.DateField(blank=True, null=True)),
                ('indexold', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
